#!/usr/bin/env ruby

require "bundler/setup"
require "mega_lotto_ps"
require_relative "../lib/mega_lotto_ps/drawing"
require_relative "../lib/mega_lotto_ps/report"

drawing = MegaLottoPs::Drawing.new.draw
puts drawing

ledger = [ [ "Deposit Check #123", 500.15],
           ["Fancy Shoes",        -200.25],
           ["Fancy Hat",           -54.40],
           ["ATM Deposit",        1200.00],
           ["Kitten Litteh",        -5.00]  ]
report = Report.new(ledger)
puts report.formatted_output         
